[build]
  command = "pip install -r requirements.txt && python -m flask run"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.11"

[dev]
  command = "python app.py"
  port = 5000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
